### ISSUE TITLE
SVG font URLs in CSS should be rewritten to use the filerev

### ISSUE THREAD

**Issue by bicycle-dev** [yeoman/grunt-usemin#221]
A very common CSS expression for loading external fonts looks like this:

``` css
@font-face {
    font-family: 'MyWebFont';
    src: url('webfont.eot');
    src: url('webfont.eot?#iefix') format('embedded-opentype'),
         url('webfont.woff') format('woff'),
         url('webfont.ttf')  format('truetype'),
         url('webfont.svg#svgFontName') format('svg');
    }

```

(from http://www.fontspring.com/blog/further-hardening-of-the-bulletproof-syntax)

The second and last URLs don't work. So URLs with a query parameter like `"?#iefix"` or with an anchor like `"#svgFontName"` don't properly get rewritten.
